[package]
name = "asyncgit"
version = "0.22.1"
authors = ["extrawurst <mail@rusticorn.com>"]
edition = "2021"
description = "allow using git2 in a asynchronous context"
homepage = "https://github.com/extrawurst/gitui"
repository = "https://github.com/extrawurst/gitui"
readme = "README.md"
license = "MIT"
categories = ["concurrency", "asynchronous"]
keywords = ["git"]

[dependencies]
crossbeam-channel = "0.5"
easy-cast = "0.5"
git2 = "0.17.2"
log = "0.4"
# git2 = { path = "../../extern/git2-rs", features = ["vendored-openssl"]}
# git2 = { git="https://github.com/extrawurst/git2-rs.git", rev="fc13dcc", features = ["vendored-openssl"]}
# pinning to vendored openssl, using the git2 feature this gets lost with new resolver
openssl-sys = { version = '0.9', features = ["vendored"], optional = true }
rayon-core = "1.11"
scopetime = { path = "../scopetime", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
shellexpand = "3.1"
thiserror = "1.0"
unicode-truncate = "0.2.0"
url = "2.3"
ssh2-config = "^0.2.0"
git-url-parse = "0.4.4"
dirs-next = "2.0"
raw_sync = "^0.1.5"
shared_memory = "^0.12.4"
anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = [ "clock" ] }

[dev-dependencies]
env_logger = "0.10"
invalidstring = { path = "../invalidstring", version = "0.1" }
pretty_assertions = "1.3"
serial_test = "1.0"
tempfile = "3.4"

[features]
default = ["trace-libgit"]
trace-libgit = []
vendor-openssl = ["openssl-sys"]
